---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll build


workflows:
  version: 2
  commit:
    jobs:
      - build
