---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-bundler-{{ checksum "Gemfile.lock" }}
            - v1-bundler-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: make build
      - run: make test


workflows:
  version: 2
  commit:
    jobs:
      - build
